{
 "title": "Testing",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "New", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Old", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Ping Pong Table Available",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pir_sensor_reading",
     "query": "SELECT max(moving_average(distinct(\"signature\"), 10)) FROM \"pir_sensor_reading\" WHERE (\"host\" = 'server01') AND $timeFilter",
     "select": [
      [
       { "params": [ "signature" ], "type": "field" },
       { "params": [ "20" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server01" }
     ]
    }
   ]
  },
  {
   "title": "PIR Sensor Signature 1 Hour",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Sensor Value Scale" }
   ],
   "targets": [
    {
     "alias": "PIR Sensor Value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pir_sensor_reading",
     "query": "SELECT moving_average(distinct(\"signature\"), 10) FROM \"pir_sensor_reading\" WHERE (\"host\" = 'server01') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "signature" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server01" }
     ]
    }
   ]
  },
  {
   "title": "GitHub Link",
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 2 },
   "content": "\n<a href=\"https://github.com/zmailloux/ping-pong-monitor\" target=\"_blank\"><img src=\"https://iconsplace.com/wp-content/uploads/_icons/fa8072/256/png/github-icon-15-256.png\" /></a>\n\n\n"
  },
  {
   "title": "Player Present",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "pir_sensor_reading",
     "select": [
      [
       { "params": [ "signature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server01" }
     ]
    }
   ]
  },
  {
   "title": "SIMULATED PIR Sensor Signature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Sensor Value Scale" }
   ],
   "targets": [
    {
     "alias": "PIR Sensor Value",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pir_sensor_reading",
     "select": [
      [
       { "params": [ "signature" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server01" }
     ]
    }
   ]
  },
  {
   "title": "Player Present in Last Minute",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pir_sensor_reading",
     "select": [
      [
       { "params": [ "signature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server01" }
     ]
    }
   ]
  },
  {
   "title": "Player Present in Last 60 Seconds",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pir_sensor_reading",
     "query": "SELECT max(moving_average(distinct(\"signature\"), 10)) FROM \"pir_sensor_reading\" WHERE (\"host\" = 'server01') AND $timeFilter",
     "select": [
      [
       { "params": [ "signature" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "server01" }
     ]
    }
   ]
  }
 ]
}