apiVersion: v1
kind: Service
metadata:
  name: dashboard-app-service
spec:
  selector:
    app: ping-pong-api
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-api
spec:
  selector:
    matchLabels:
      app: ping-pong-api
  replicas: 1
  template:
    metadata:
      labels:
        app: ping-pong-api
    spec:
      containers:
      - name: ping-pong-api
        image: gcr.io/precise-space-265115/ping-pong-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: redirect_url
            value: "http://35.223.162.100/"
